PROJECT_TYPES = {"CAPTURE", "UPLOAD", "AI_VIDEO", "EDITING_ONLY"}

ARTIFACT_TYPES = {
    "RAW_VIDEO",
    "RAW_AUDIO",
    "EXTRACTED_AUDIO",
    "TRANSCRIPT",
    "SUBTITLE",
    "FRAME",
    "THUMBNAIL",
    "AI_SCRIPT",
    "AI_STORYBOARD",
    "AI_PROMPT",
    "AI_PROVIDER_REQUEST",
    "AI_PROVIDER_RESPONSE",
    "RAW_AI_VIDEO",
    "EDIT_PLAN",
    "EDITED_VIDEO",
    "EXPORT_PACKAGE",
    "REPORT",
}
